// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm83p5DzJkGlmG5nQvzOOPzsxYaNklBCM',
    appId: '1:126154070685:web:f4822a25b25ae2041f5274',
    messagingSenderId: '126154070685',
    projectId: 'ravel-booking-app',
    authDomain: 'ravel-booking-app.firebaseapp.com',
    storageBucket: 'ravel-booking-app.firebasestorage.app',
    measurementId: 'G-GKB82NM3N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4lADqqOhRYUvrfAKpQL-AImixocCxmQ',
    appId: '1:126154070685:android:e51fa0037f6cad071f5274',
    messagingSenderId: '126154070685',
    projectId: 'ravel-booking-app',
    storageBucket: 'ravel-booking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Yl_iLpkFAHcUioD5DiBxFcjGdDY_g1I',
    appId: '1:126154070685:ios:82500d042db856371f5274',
    messagingSenderId: '126154070685',
    projectId: 'ravel-booking-app',
    storageBucket: 'ravel-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.trevelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Yl_iLpkFAHcUioD5DiBxFcjGdDY_g1I',
    appId: '1:126154070685:ios:82500d042db856371f5274',
    messagingSenderId: '126154070685',
    projectId: 'ravel-booking-app',
    storageBucket: 'ravel-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.trevelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm83p5DzJkGlmG5nQvzOOPzsxYaNklBCM',
    appId: '1:126154070685:web:eea4fa20744d67f11f5274',
    messagingSenderId: '126154070685',
    projectId: 'ravel-booking-app',
    authDomain: 'ravel-booking-app.firebaseapp.com',
    storageBucket: 'ravel-booking-app.firebasestorage.app',
    measurementId: 'G-ZTJM75VH0S',
  );

}